#include "colour.h"
#include <stdlib.h>
#include <string.h>
static int ertf_colour_add(FILE *);
int ertf_colortbl(FILE *fp){
  int c;
  while((c=fgetc(fp))!=EOF){
    switch(c){
    case ';':// indicates default font
      break;
    case '\\':
      ungetc(c, fp);
      if(ertf_colour_add(fp))
	continue;
      else
	fprintf(stderr, "colortbl: Ill-formed rtf\n");
      break;
    case '}':// end of colour table
      return 1;
    default:
      fprintf(stderr, "colortbl: Ill-formed rtf");
      return 0;
    }
  }
  fprintf(stderr, "End of file reached in colour table.\n");
  return 0;
}
/*
 * This functions adds an entry to the colour table. It returns 1 on success and
 * 0 in case of failure.
 */
static int ertf_colour_add(FILE *fp){
  char colour[7];
  char index;
  COLOUR *node=(COLOUR *)malloc(sizeof(COLOUR));
  int c;
  while((c=fgetc(fp))!=EOF){
    switch(c){
    case '\\':
      ungetc(c, fp);
      fscanf(fp, "%[^0123456789]", colour);
      if(feof(fp)) goto err;
      fscanf(fp, "%d", &index);// todo: remove warning generated by this line
      if(feof(fp)) goto err;
      if(strcmp(colour, "\\green") == 0)
	node->g = index;
      else if(strcmp(colour, "\\red")==0)
	node->r=index;
      else if(strcmp(colour, "\\blue")==0)
	node->b=index;
      else
	// continue as the tag is not recognised and should be therefore skipped
	fprintf(stderr, "Warning: skipped tag \"%s\".\n", colour);
      break;
    case ';':// todo: add the entry to a eina array or list as appropriate
      return 1;
    default:
      fprintf(stderr, "Ill-formed rtf file.\n");
      goto err;
    }    
  }
 err:
  free(node);
  return 0;
}
